### ISSUE TITLE
No rule to make target 'install-tools'

### ISSUE THREAD

**Issue by ecsuae** [bramp/myip#9]
i installed google cloud sdk, cloned your repo and inside folder myip when i run make install-tools i get error 
make: *** No rule to make target 'install-tools'.  Stop.

can you guide what is wrong ?

**Comment by bramp** [comment]
I removed `install-tools` in my last update, but didn't update the readme. You can just skip that step.

**Comment by ecsuae** [comment]
i tried it couple of times still no luck ,i am using ubuntu 20.04 server without gui, i ran following commands:
git clone https://github.com/bramp/myip.git
    cd myip/
    apt-get install apt-transport-https ca-certificates gnupg
    echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
    apt-get update && sudo apt-get install google-cloud-sdk
    apt-get install google-cloud-sdk-app-engine-go
   dig ip.bramp.net
   make deploy
   apt install make
   make deploy
   make stage
   make check-updates
   apt install nodejs
   apt install npm
   make check-updates
   make test
   apt install yarn
   make test
   make check-updates

i get error on all make commands.

make check-updates
/root/myip/node_modules/.bin/ncu
make: /root/myip/node_modules/.bin/ncu: Command not found
make: *** [Makefile:30: check-updates] Error 127

make test
yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
make: *** [Makefile:27: static/bower_components] Error 1

your help appreciated.
